apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  name: broker-a
  annotations:
    # case-sensitive
    eventing.knative.dev/broker.class: Kafka
spec:
  config:
    apiVersion: v1
    kind: ConfigMap
    name: kafka-broker-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-broker-config
data:
  default.topic.partitions: "4"
  default.topic.replication.factor: "1"
  bootstrap.servers: "my-cluster-kafka-bootstrap.kafka:9092"
