apiVersion: sources.knative.dev/v1
kind: ContainerSource
metadata:
  name: event-emitter
spec:
  template:
    spec:
      containers:
      - image: ghcr.io/michaelvl/knative-katas@sha256:67ec9c1f7aed35878feb071c206d0aa56a2c7aac0826cd1eca1301f595ac8bd9
        workingDir: /apps/event-emitter
        env:
         - name: APP_DATA
           value : '{"msg": "Hello from container source through broker!"}'
         - name: APP_CRON_SCHEDULE
           value : '*/5 * * * * *'
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: broker-a
