apiVersion: sources.knative.dev/v1
kind: ContainerSource
metadata:
  name: event-emitter1
spec:
  template:
    spec:
      containers:
      - image: ghcr.io/michaelvl/knative-katas@sha256:4b3d49ac8ffe76db79415162fcf074b6ed9d8bebb0d2d168df2bddc458dbd56f
        workingDir: /apps/event-emitter
        env:
         - name: APP_DATA
           value : '{"msg": "Hello from container source 1 through parallel!"}'
         - name: APP_CRON_SCHEDULE
           value : '*/10 * * * * *'
         - name: APP_EVENT_SOURCE 
           value : 'emitter1'
  sink:
    ref:
      apiVersion: flows.knative.dev/v1
      kind: Parallel
      name: copy-events
