apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-event-emitter
spec:
  selector:
    matchLabels:
      app: event-emitter
  template:
    metadata:
      labels:
        app: event-emitter
    spec:
      containers:
      - image: ghcr.io/michaelvl/knative-katas@sha256:24a31c707d9997934cc27631a24b189ea8aa5bba59037d259f2de11d5ed32bb3
        name: event-emitter
        workingDir: /apps/event-emitter
        env:
         - name: APP_DATA
           value : '{"msg": "Hello from deployment-based source!"}'
