apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-event-emitter
spec:
  selector:
    matchLabels:
      app: event-emitter
  template:
    metadata:
      labels:
        app: event-emitter
    spec:
      containers:
      - image: ghcr.io/michaelvl/knative-katas@sha256:4b3d49ac8ffe76db79415162fcf074b6ed9d8bebb0d2d168df2bddc458dbd56f
        name: event-emitter
        workingDir: /apps/event-emitter
        env:
         - name: APP_DATA
           value : '{"msg": "Hello from deployment-based source!"}'
