apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: event-logger
spec:
  template:
    spec:
      containers:
      - image: ghcr.io/michaelvl/knative-katas@sha256:4b3d49ac8ffe76db79415162fcf074b6ed9d8bebb0d2d168df2bddc458dbd56f
        env:
         - name: APP_DISCARD_RESPONSE
           value : "1"
