apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: filter1
spec:
  template:
    spec:
      containers:
      - image: ghcr.io/michaelvl/knative-katas@sha256:67ec9c1f7aed35878feb071c206d0aa56a2c7aac0826cd1eca1301f595ac8bd9
        workingDir: /apps/filter
        env:
         - name: APP_FILTER_KEY
           value : 'msg'
         - name: APP_FILTER_VALUE
           value : 'source 1'
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: filter2
spec:
  template:
    spec:
      containers:
      - image: ghcr.io/michaelvl/knative-katas@sha256:67ec9c1f7aed35878feb071c206d0aa56a2c7aac0826cd1eca1301f595ac8bd9
        workingDir: /apps/filter
        env:
         - name: APP_FILTER_KEY
           value : 'msg'
         - name: APP_FILTER_VALUE
           value : 'source 2'
