apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: filter1
spec:
  template:
    spec:
      containers:
      - image: ghcr.io/michaelvl/knative-katas@sha256:cf45b93f2b1ac2640a5e1366f78d1a1a6e1d3a575460c7e99b1aa5e35c26607e
        workingDir: /apps/filter
        env:
         - name: APP_FILTER_KEY
           value : 'msg'
         - name: APP_FILTER_VALUE
           value : 'source 1'
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: filter2
spec:
  template:
    spec:
      containers:
      - image: ghcr.io/michaelvl/knative-katas@sha256:cf45b93f2b1ac2640a5e1366f78d1a1a6e1d3a575460c7e99b1aa5e35c26607e
        workingDir: /apps/filter
        env:
         - name: APP_FILTER_KEY
           value : 'msg'
         - name: APP_FILTER_VALUE
           value : 'source 2'
