apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: filter1
spec:
  template:
    spec:
      containers:
      - image: ghcr.io/michaelvl/knative-katas@sha256:eb09ef8d1f5124c1e2348f4d4eeca8075b83e44f7c5157ea68c6c656f223dc98
        workingDir: /apps/filter
        env:
         - name: APP_FILTER_KEY
           value : 'msg'
         - name: APP_FILTER_VALUE
           value : 'source 1'
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: filter2
spec:
  template:
    spec:
      containers:
      - image: ghcr.io/michaelvl/knative-katas@sha256:eb09ef8d1f5124c1e2348f4d4eeca8075b83e44f7c5157ea68c6c656f223dc98
        workingDir: /apps/filter
        env:
         - name: APP_FILTER_KEY
           value : 'msg'
         - name: APP_FILTER_VALUE
           value : 'source 2'
