apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: filter1
spec:
  template:
    spec:
      containers:
      - image: ghcr.io/michaelvl/knative-katas@sha256:24a31c707d9997934cc27631a24b189ea8aa5bba59037d259f2de11d5ed32bb3
        workingDir: /apps/filter
        env:
         - name: APP_FILTER_KEY
           value : 'msg'
         - name: APP_FILTER_VALUE
           value : 'source 1'
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: filter2
spec:
  template:
    spec:
      containers:
      - image: ghcr.io/michaelvl/knative-katas@sha256:24a31c707d9997934cc27631a24b189ea8aa5bba59037d259f2de11d5ed32bb3
        workingDir: /apps/filter
        env:
         - name: APP_FILTER_KEY
           value : 'msg'
         - name: APP_FILTER_VALUE
           value : 'source 2'
