apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: filter1
spec:
  template:
    spec:
      containers:
      - image: ghcr.io/michaelvl/knative-katas@sha256:4b3d49ac8ffe76db79415162fcf074b6ed9d8bebb0d2d168df2bddc458dbd56f
        workingDir: /apps/filter
        env:
         - name: APP_FILTER_KEY
           value : 'msg'
         - name: APP_FILTER_VALUE
           value : 'source 1'
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: filter2
spec:
  template:
    spec:
      containers:
      - image: ghcr.io/michaelvl/knative-katas@sha256:4b3d49ac8ffe76db79415162fcf074b6ed9d8bebb0d2d168df2bddc458dbd56f
        workingDir: /apps/filter
        env:
         - name: APP_FILTER_KEY
           value : 'msg'
         - name: APP_FILTER_VALUE
           value : 'source 2'
