apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: simple
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/target: "1"
    spec:
      containers:
      - image: ghcr.io/michaelvl/knative-katas@sha256:67ec9c1f7aed35878feb071c206d0aa56a2c7aac0826cd1eca1301f595ac8bd9
        env:
         - name: APP_HTTP_STATUS_CODE
           value : "200"
         - name: APP_DISCARD_RESPONSE
           value : "1"
         - name: APP_HTTP_LOG
           value : "1"
         - name: APP_EVENT_LOG
           value : "1"
