apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: simple
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/target: "1"
    spec:
      containers:
      - image: wbitt/network-multitool
        ports:
         - containerPort: 80
