apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: trigger1
spec:
  broker: broker-a
  filter:
    attributes:
      type: type-example
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: simple
