apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  labels:
    app: sentences
    mode: age
  name: age
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/target: "1"
    spec:
      containers:
      - image: ghcr.io/michaelvl/istio-katas@sha256:430d3a01a502c2b13af2619ad41f2247e6e46282e1c100db4f27c917b2867555
        name: age
        args:
        - /usr/src/app-grpc/sentences.py
        env:
        - name: "SENTENCE_MODE"
          value: "age"
        ports:
        - name: h2c
          containerPort: 5000
