apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  labels:
    app: sentences
    mode: age
  name: age
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/target: "1"
    spec:
      containers:
      - image: ghcr.io/michaelvl/istio-katas@sha256:4a26235a20b67c1a0650da8ad28d901a9942af52ab9dad09f283c2142f256d4c
        name: age
        args:
        - /usr/src/app-grpc/sentences.py
        env:
        - name: "SENTENCE_MODE"
          value: "age"
        ports:
        - name: h2c
          containerPort: 5000
